run:
  timeout: 5m

linters:
  disable-all: true
  enable:
    - bodyclose
    - dogsled
    - dupl
    - durationcheck
    - exhaustive
    - exportloopref
    - gci
    - gofmt
    - gofumpt
    - goimports
    - gomoddirectives
    - goprintffuncname
    - govet
    - importas
    - ineffassign
    - makezero
    - misspell
    - nakedret
    - nilerr
    - noctx
    - nolintlint
    - prealloc
    - predeclared
    - revive
    - sqlclosecheck
    - staticcheck
    - stylecheck
    - tparallel
    - typecheck
    - unconvert
    - unparam
    - unused
    - whitespace

    # fixme
    # - cyclop
    # - errcheck
    # - errorlint
    # - exhaustivestruct
    # - forbidigo
    # - forcetypeassert
    # - gochecknoglobals
    # - gochecknoinits
    # - gocognit
    # - goconst
    # - gocritic
    # - gocyclo
    # - godot
    # - gosec
    # - gosimple
    # - ifshort
    # - lll
    # - nlreturn
    # - paralleltest
    # - scopelint
    # - thelper
    # - wrapcheck

    # unused
    # - deadcode
    # - depguard
    # - goheader
    # - gomodguard
    # - rowserrcheck
    # - structcheck
    # - varcheck
    # - wastedassign


    # don't enable:
    # - asciicheck
    # - funlen
    # - godox
    # - goerr113
    # - gomnd
    # - interfacer
    # - maligned
    # - nestif
    # - testpackage
    # - wsl